language: ruby
cache: bundler
dist: xenial

before_install:
  - gem install bundler || true
  - bundle --version
  - gem update --system
  - gem --version

matrix:
  include:
    - rvm: 2.6.3
    - rvm: 2.7.2

bundler_args: --jobs 7

script: bundle exec rake
